/**
  ******************************************************************************
  * @file    main.c
  * @author  Auto-generated by STM32CubeIDE
  * @version V1.0
  * @brief   Default main function.
  ******************************************************************************
*/

#include "stm32l053_MemMap.h"
#include "stm32l053_gpio_driver.h"
#include "stm32l053_rcc_regMap.h"

gpio_handle_t myGPIO;




int main(void)
{



	for(;;);
}
